on:
    push:

jobs:
    build-java:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # version 7.0.0
            
            - name: setup java
              uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # version 5.5.0
            
            - name: build app
              run: |
                chmod +x gradlew
                ./gradlew tasks
                