on:
    push:

jobs:
    build-java:
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: read
        steps:
            - name: checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # version 7.0.0
            
            - name: setup java
              uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # version 5.5.0
              with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '25'
            
            - name: unit tests
              run: |
                chmod +x gradlew
                # ./gradlew tasks
                ./gradlew test

            - name: build docker
              run: |
                docker build -t ghcr.io/jairocc/cloudcamp-gradle/javamicro:latest .
            
            - name: docker login
              env:
                gh_pat: GITHUB_TOKEN
              run: |
                echo "${gh_pat}" | docker login ghcr.io -u JairoCC --password-stdin 
            
            - name: docker push
              run: |
                docker push ghcr.io/jairocc/cloudcamp-gradle/javamicro:latest
                