on:
    push:

jobs:
    build-java:
        runs-on: ubuntu-latest
        permissions:
          packages: write
          contents: read
        steps:
            - name: checkout
              uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # version 7.0.0
            
            - name: setup java
              uses: actions/setup-java@0f481fcb613427c0f801b606911222b5b6f3083a # version 5.5.0
              with:
                distribution: 'temurin' # See 'Supported distributions' for available options
                java-version: '25'
            
            - name: unit tests
              run: |
                chmod +x gradlew
                # ./gradlew tasks
                ./gradlew test
            
            - name: docker setup
              uses: docker/setup-buildx-action@v4

            - name: docker login
              uses: docker/login-action@v4
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ github.token }}

            - name: generate tag
              id: generate_tag
              run: |
                tag=$(echo "${{ github.repository }}" | tr "[:upper:]" "[:lower:]")
                tag="ghcr.io/${tag}/javamicro:latest"
                echo "TAG=${tag}" >> $GITHUB_OUTPUT

            - name: docker build and push
              uses: docker/build-push-action@v7
              with:
                push: ${{ github.ref_name == 'main' }}
                tags: ${{ steps.generate_tag.outputs.TAG }}